/* confdefs.h */
#define PACKAGE_NAME "libsamplerate"
#define PACKAGE_TARNAME "libsamplerate"
#define PACKAGE_VERSION "0.1.8"
#define PACKAGE_STRING "libsamplerate 0.1.8"
#define PACKAGE_BUGREPORT "erikd@mega-nerd.com"
#define PACKAGE_URL "http://www.mega-nerd.com/libsamplerate/"
#define PACKAGE "libsamplerate"
#define VERSION "0.1.8"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define HAVE_STDINT_H 1
